version: "3"

tasks:
  poetry:
    desc: Init poetry
    cmds:
      - poetry init
      - poetry shell
      - poetry add pytest
      - poetry install

  tests:
    cmds:
      - poetry shell
      - poetry run pytest
